apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: search
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
    spec:
      containers:
      - image: us-west2-docker.pkg.dev/pulsar-357404/package-frontend/search:1.0.5
        volumeMounts:
        - name: GCS
          mountPath: /usr/src/app/mnt
      volumes:
      - name: GCS
        csi:
          driver: gcsfuse.run.googleapis.com
          readOnly: False
          volumeAttributes:
            bucketName: pulsar-search-microservice
